version: '3.7'
services:
    postgres:
        image: docker.io/ankane/pgvector:latest
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=testing
          - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/testing
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5438:5432'
        volumes: 
          - ./volumes:/var/lib/postgresql/data
    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4
        restart: always
        environment:
          PGADMIN_DEFAULT_EMAIL: admin@admin.com
          PGADMIN_DEFAULT_PASSWORD: root
        ports:
          - "5050:80"
        volumes:
          - ./volumes/pg-admin:/var/lib/pgadmin